version: "3.8"
services:
  nuxeo:
    image: msoffice-url-fixer:2021.1.0
    #TODO create '.env' file. See sample '.env.sample' and set 'NUXEO_CLID' with a valid CLID
    env_file: .env
    ports:
      - "8080:8080"
      - "8787:8787"
    environment:
      NUXEO_DEV: "true"
      NUXEO_PACKAGES: nuxeo-web-ui
    volumes:
      - ./conf.d:/etc/nuxeo/conf.d
      - data:/var/lib/nuxeo
      - lib:/var/lib/nuxeo
      - log:/var/log/nuxeo
      - tmp:/tmp
volumes:
  data: {}
  tmp: {}
  lib: {}
  log: {}
